{% set name = "dash-bio-utils" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dash_bio_utils-{{ version }}.tar.gz
  sha256: b6e66ce5e7b9233b24286ed94e6b55ee73571955f9e6ca2d9efce99d3162bd19

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - biopython
    - colour
    - geoparse >=1.1.0
    - jsonschema
    - pandas
    - parmed
    - periodictable
    - python >=3.6
    - requests
    - typing_extensions

test:
  imports:
    - dash_bio_utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/plotly/dash-bio-utils
  summary: Simple parsing tools that supplement dash-bio.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
